### ISSUE TITLE
GCE Support

### ISSUE THREAD

**Issue by btickell** [geyang/jaynes#1]
It seems like the GCE support hasn't been touched in a while. I remember using jaynes with GCP a year back but now seems the CLI is deprecated? There doesn't seem to be a way to mount an output directory analogous to the S3OutputMount construction. Am I using an out of date tutorial or is the feature broken?

**Comment by geyang** [comment]
It works really well and is currently used in production.

**Comment by btickell** [comment]
What is the preferred way to mount result files to GS?

**Comment by geyang** [comment]
Here is the example for gcp:

10_gcp_docker_example

**Comment by geyang** [comment]
Here is the relevant tutorial: see the yml file:

https://github.com/geyang/jaynes-starter-kit/tree/master/10_gcp_docker_example

**Comment by btickell** [comment]
Yes have found this tutorial quite helpful.These are both code mounts right?
```
mounts:
  - !mounts.GSCode
    prefix: "gs://{env.JYNS_GS_BUCKET}/jaynes-debug"
    local_path: .
    host_path: "$HOME/jaynes-mounts/{now:%Y-%m-%d}/{now:%H%M%S.%f}/code-mount"
    pypath: true
    excludes: >-
      --exclude='*__pycache__' --exclude='*.git' --exclude='*.idea' --exclude='*.egg-info'
      --exclude='*.pkl'
    compress: true
  - !mounts.GSCode
    prefix: "gs://{env.JYNS_GS_BUCKET}/.gce"
    local_path: "$HOME/.gce"
    host_path: "$HOME/jaynes-mounts/{now:%Y-%m-%d}/{now:%H%M%S.%f}/.gce"
    file_mask: "$USER-improbable-gs-service.json"
    container_path: /root/.gce
    compress: true
```

 They tar the directory and mount it in the docker container but do not sync the mount back to GCE storage during the lifetime of the instance. I was looking for something similar to `S3Output` for GCE.
